spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toy_test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: chldudwls12!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
